---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	planner(planner)
	interviewer(interviewer)
	analyst(analyst)
	__end__([<p>__end__</p>]):::last
	__start__ -.-> interviewer;
	__start__ -.-> planner;
	interviewer -.-> __end__;
	interviewer -.-> analyst;
	planner --> interviewer;
	analyst --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
